"""changed rating from float to integer

Revision ID: 91995f83695a
Revises: b7da42901333
Create Date: 2025-03-02 12:24:19.576419

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91995f83695a'
down_revision: Union[str, None] = 'b7da42901333'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reviews', 'rating',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Integer(),
               existing_nullable=False)
    # op.alter_column('users', 'role',
    #            existing_type=sa.VARCHAR(),
    #            type_=sa.Enum('USER', 'ADMIN', name='userrole'),
    #            existing_nullable=False,
    #            existing_server_default=sa.text("'user'::character varying"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.alter_column('users', 'role',
    #            existing_type=sa.Enum('USER', 'ADMIN', name='userrole'),
    #            type_=sa.VARCHAR(),
    #            existing_nullable=False,
    #            existing_server_default=sa.text("'user'::character varying"))
    op.alter_column('reviews', 'rating',
               existing_type=sa.Integer(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    # ### end Alembic commands ###
