"""added location, logo, number and website to business model

Revision ID: e3fdb3093596
Revises: 99f12a4dbe44
Create Date: 2025-04-29 10:25:17.088399

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'e3fdb3093596'
down_revision: Union[str, None] = '99f12a4dbe44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('businesses', sa.Column('location', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('businesses', sa.Column('logo', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('businesses', sa.Column('number', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('businesses', sa.Column('website', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('businesses', 'website')
    op.drop_column('businesses', 'number')
    op.drop_column('businesses', 'logo')
    op.drop_column('businesses', 'location')
    # ### end Alembic commands ###
